### ISSUE TITLE
generating clinically related multiple choice question? 

### ISSUE THREAD

**Issue by 2533245542** [jondurbin/airoboros#13]
Is it possible to generate clinically relevant multiple choice question? I skimmed through the config and didn't see an obvious way to do way. 

I am thinking of some thing like

```
Q: which note category does the belong clinical note belong to?

[clinical note]

(A). phone encounter
(B). nursing notes
(C). progress notes
(D). discharge summary
(E). others

A:

```

**Comment by jondurbin** [comment]
I added a multiple choice instructor this morning (version 2.0.14):
https://github.com/jondurbin/airoboros/commit/8433793870b8cbbe21c1f730ced8cea6b0edab84

Basically, you'll want to setup your config to include:
```
instructors:
  multiple_choice:
    api_params:
      temperature: 0.3
    count: 10
    batch_size: 5
    min_docsearch_score: 0.1
    contextual_ratio: 0.2
    topics_path: topics.txt
```

You'll probably want to change the count, but I would leave the batch size as 5, as the quality/length of contextual questions drops with larger batch size.

You may want to change contextual_ratio as well.  This dictates how many of the questions have a paragraph of text associated with them.  If you want them to all be contextual, this should be 1.0

You can also change topics_path for this particular instructor to have your own list, distinct from the main topics.txt if you want to include general instructions as well.

If you have a list of topics, great - save it to a text fine, one line per topic, otherwise you may also want to change the `topic_prompt` value to something like "Give me a numbered list of 20 completely random topics related to healthcare. {topic_avoidance}"  I would also update topic_avoidance accordingly.
